### ISSUE TITLE
Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider

### ISSUE THREAD

**Issue by javierpal** [EddyVerbruggen/nativescript-admob#43]
For some reason I get this error, the only thing i recall doing is test the ios version of the app for the first time so i installed the cocoa pods and run it in ios and it worked, then i try to run it in android again and the app does not even start, this is the complete error log.

`FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException

                                                                              * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
                                                                              * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
                                                                              * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
                                                                              * follow instructions here: https://goo.gl/h17b6x.                           *

                                                                                  at android.app.ActivityThread.installProvider(ActivityThread.java:5177)
                                                                                  at android.app.ActivityThread.installContentProviders(ActivityThread.java:4769)
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4709)
                                                                                  at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                               Caused by: java.lang.IllegalStateException: `

**Comment by shilik** [comment]
@javierpal I've got the same errors too. I have followed the instruction stated in https://goo.gl/fQ2neu 
by adding 

<manifest>
    <application>
        
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-################~##########"/>
    </application>
</manifest>

But unfortunately, nothing has changed!

here you can get more info about the errors, https://ads-developers.googleblog.com/2018/10/announcing-v1700-of-android-google.html
has mentioned about the change of admob sdk.

**Comment by javierpal** [comment]
@shilik it's weird because i did it too and it worked fine later, one more thing the only line you need to add is: 
`<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="[ADMOB_APP_ID]"/>`

inside manifest/application check if you have it right.

**Comment by shilik** [comment]
@javierpal 
Yes, it is quite wierd.
I have tried  either
`<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="[ADMOB_APP_ID]"/>`  
or
`<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ADMOB_APP_ID"/>`
then did the following 
npm run clean 
adb logcat -d >log.txt
npm run watch:android

but 
my app kept stopped and crached. :(

**Comment by shilik** [comment]
@javierpal 

I have tried various combinations.
when the code snippets are added,  The "The Google Mobile Ads SDK was initialized incorrectly. "
error disappeared. but my app crashed.
finding:
As long as nativescript-admob is installed (whatever version),
my app crashed and stopped after re-compilation.

**Comment by kingkarki** [comment]
I am getting following error while running on android device 

******************************************************************************
11-22 14:20:45.942  5293  5293 E AndroidRuntime: * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
11-22 14:20:45.942  5293  5293 E AndroidRuntime: * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
11-22 14:20:45.942  5293  5293 E AndroidRuntime: * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
11-22 14:20:45.942  5293  5293 E AndroidRuntime: * follow instructions here: https://goo.gl/h17b6x.                           *
11-22 14:20:45.942  5293  5293 E AndroidRuntime: ******************************************************************************

I am not using any google AdMob plugin. 
I am using following plugins 

```
cordova-facebook-audnet-sdk 4.26.2 "Facebook AudienceNetwork SDK for Cordova"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-facebookads 4.23.2 "FacebookAds"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.3 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Comment by bereket-kassahun** [comment]
"... AT THE END OF THE MANIFEST/APPLICATION ", after two days of trial i finally get rid of the error.
grate answer thank you!!

**Comment by EddyVerbruggen** [comment]
@bereket-kassahun Just so I can make sure the instructions in this repo are still correcht, is your solution any different than [adding this](https://github.com/EddyVerbruggen/nativescript-admob/blob/402c9ffc63a9e8a8972d55697a3e665e27da8a99/demo/app/App_Resources/Android/src/main/AndroidManifest.xml#L28) and the instruction [here](https://github.com/EddyVerbruggen/nativescript-admob#android)? If so, how can we make that more clear?

**Comment by TawfiqHasan** [comment]
though i put this code on my manifest file but still my app is crushed

<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="[ADMOB_APP_ID]"/>

**Comment by TawfiqHasan** [comment]
> though i put this code on my manifest file but still my app is crushed
manifest:
<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="[ADMOB_APP_ID]"/>

**Comment by willagner** [comment]
> "... AT THE END OF THE MANIFEST/APPLICATION ", after two days of trial i finally get rid of the error.
> grate answer thank you!!

i had this problem to...

"... AT THE END OF THE MANIFEST/APPLICATION "
