### ISSUE TITLE
Conflict while using this plugin with google analytics plugin

### ISSUE THREAD

**Issue by hakanu** [EddyVerbruggen/nativescript-admob#8]
Hi,

I've been trying to use this plugin however, my app doesn't build for android.
This is the stacktrace:
:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class com.google.android.gms.internal.zzk$zza conflict: /Users/path/to/platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-basement/9.0.2/jars/classes.jar and /Users/path/to/platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-ads/7.5.0/jars/classes.jar
  at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
  at com.telerik.metadata.Builder.build(Builder.java:39)
  at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.

This is the other plugin: https://www.npmjs.com/package/nativescript-google-analytics

Any idea is welcome! Thanks.

**Comment by hakanu** [comment]
as a side note, i guess it's not related to analytics plugin.
I removed analytics plugin but it still throws the same error during the building.

**Comment by EddyVerbruggen** [comment]
I just changed the gradle include - can you remove the plugin and android platform, and re-add them? Please check that [this change](https://github.com/EddyVerbruggen/nativescript-admob/blob/master/platforms/android/include.gradle#L10) is part of your build.

**Comment by hakanu** [comment]
Thanks for the fast reply Eddy!
I removed the plugin, added again, deleted node_modules and platform/android folders and rebuilt it but still have the same problem :/

I don't have include.gradle btw under my platforms.
